---
  name: PART3 - CH1 - Condition 1
  on: workflow_dispatch
  jobs:
    variables:
      runs-on: ubuntu-latest
      steps:
        - name: Print GitHub Variables
          env:
            GITHUB_CONTEXT: ${{ toJSON(github) }}
          run: echo $GITHUB_CONTEXT
    # build:
    #   if: ${{ github.repository == 'devbluemoons/github-action-course' }}
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Step 1
    #     run: |
    #       echo "Run Step 1, Say Hello"
    #   - name: Step 2
    #     if: ${{ github.event_name == 'workflow_dispatch' }}
    #     run: |
    #       echo "Run Step 2, Say Hello"
      
